USE [Base]
GO

/****** Object:  Table [dbo].[Bairro]    Script Date: 15/04/2020 09:36:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Bairro](
	[IdBairro] [int] IDENTITY(1,1) NOT NULL,
	[IdCidade] [int] NULL,
	[Descrição] [ntext] NULL,
 CONSTRAINT [PK_Bairro] PRIMARY KEY CLUSTERED 
(
	[IdBairro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

