'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
'
Namespace ConsultaResultProt

    'CODEGEN: O elemento de extensão WSDL opcional 'PolicyReference' do espaço para nome 'http://schemas.xmlsoap.org/ws/2004/09/policy' não foi tratado.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Web.Services.WebServiceBindingAttribute(Name:="Servicos.Empregador_ServicoConsultarLoteEventos", [Namespace]:="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" &
        "Processamento/v1_1_0")>
    Partial Public Class ServicoConsultarLoteEventos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultarLoteEventosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean

        '''<remarks/>
        Public Sub New(myBinding As ServiceModel.BasicHttpsBinding)
            MyBase.New
            Me.Url = "https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/consultarloteeventos/WsConsultarLoteEventos.svc?singleWsdl"
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultarLoteEventosCompleted As ConsultarLoteEventosCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" &
            "Processamento/v1_1_0/ServicoConsultarLoteEventos/ConsultarLoteEventos", RequestNamespace:="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" &
            "Processamento/v1_1_0", ResponseNamespace:="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" &
            "Processamento/v1_1_0", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Function ConsultarLoteEventos(ByVal consulta As System.Xml.XmlElement) As System.Xml.XmlElement
            Dim results() As Object = Me.Invoke("ConsultarLoteEventos", New Object() {consulta})
            Return CType(results(0),System.Xml.XmlElement)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteEventosAsync(ByVal consulta As System.Xml.XmlElement)
            Me.ConsultarLoteEventosAsync(consulta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteEventosAsync(ByVal consulta As System.Xml.XmlElement, ByVal userState As Object)
            If (Me.ConsultarLoteEventosOperationCompleted Is Nothing) Then
                Me.ConsultarLoteEventosOperationCompleted = AddressOf Me.OnConsultarLoteEventosOperationCompleted
            End If
            Me.InvokeAsync("ConsultarLoteEventos", New Object() {consulta}, Me.ConsultarLoteEventosOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarLoteEventosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarLoteEventosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarLoteEventosCompleted(Me, New ConsultarLoteEventosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarLoteEventosCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarLoteEventosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarLoteEventosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlElement
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlElement)
            End Get
        End Property
    End Class
End Namespace
