'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Comercial")>  _
Partial Public Class LqComercialDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertFormasPGOrcamento(instance As FormasPGOrcamento)
    End Sub
  Partial Private Sub UpdateFormasPGOrcamento(instance As FormasPGOrcamento)
    End Sub
  Partial Private Sub DeleteFormasPGOrcamento(instance As FormasPGOrcamento)
    End Sub
  Partial Private Sub InsertOrcamentos(instance As Orcamentos)
    End Sub
  Partial Private Sub UpdateOrcamentos(instance As Orcamentos)
    End Sub
  Partial Private Sub DeleteOrcamentos(instance As Orcamentos)
    End Sub
  Partial Private Sub InsertProdutosOrcamento(instance As ProdutosOrcamento)
    End Sub
  Partial Private Sub UpdateProdutosOrcamento(instance As ProdutosOrcamento)
    End Sub
  Partial Private Sub DeleteProdutosOrcamento(instance As ProdutosOrcamento)
    End Sub
  Partial Private Sub InsertPedidoOnLine(instance As PedidoOnLine)
    End Sub
  Partial Private Sub UpdatePedidoOnLine(instance As PedidoOnLine)
    End Sub
  Partial Private Sub DeletePedidoOnLine(instance As PedidoOnLine)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CRM_BASE.My.MySettings.Default.ComercialConnectionString3, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property FormasPGOrcamento() As System.Data.Linq.Table(Of FormasPGOrcamento)
		Get
			Return Me.GetTable(Of FormasPGOrcamento)
		End Get
	End Property
	
	Public ReadOnly Property Orcamentos() As System.Data.Linq.Table(Of Orcamentos)
		Get
			Return Me.GetTable(Of Orcamentos)
		End Get
	End Property
	
	Public ReadOnly Property ProdutosOrcamento() As System.Data.Linq.Table(Of ProdutosOrcamento)
		Get
			Return Me.GetTable(Of ProdutosOrcamento)
		End Get
	End Property
	
	Public ReadOnly Property PedidoOnLine() As System.Data.Linq.Table(Of PedidoOnLine)
		Get
			Return Me.GetTable(Of PedidoOnLine)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.DeletaOrcamento")>  _
	Public Function DeletaOrcamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrcamento", DbType:="Int")> ByVal idOrcamento As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idOrcamento)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AtualizavalorItemOrcamento")>  _
	Public Function AtualizavalorItemOrcamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdItemProdutoOrcamento", DbType:="Int")> ByVal idItemProdutoOrcamento As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Idproduto", DbType:="Int")> ByVal idproduto As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdSolicitacao", DbType:="Int")> ByVal idSolicitacao As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ValorUnit", DbType:="Money")> ByVal valorUnit As System.Nullable(Of Decimal)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idItemProdutoOrcamento, idproduto, idSolicitacao, valorUnit)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.DeletaItensOrcamento")>  _
	Public Function DeletaItensOrcamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrcamento", DbType:="Int")> ByVal idOrcamento As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Versao", DbType:="Int")> ByVal versao As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idOrcamento, versao)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InsereNovaFormaPgOrcamento")>  _
	Public Function InsereNovaFormaPgOrcamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdForma", DbType:="Int")> ByVal idForma As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrcamento", DbType:="Int")> ByVal idOrcamento As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdVersao", DbType:="Int")> ByVal idVersao As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Valor", DbType:="Money")> ByVal valor As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Pc", DbType:="NText")> ByVal pc As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Vencimento", DbType:="Date")> ByVal vencimento As System.Nullable(Of Date)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idForma, idOrcamento, idVersao, valor, pc, vencimento)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.DeletaFormasPgOrcamentoOrcamento")>  _
	Public Function DeletaFormasPgOrcamentoOrcamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrcamento", DbType:="Int")> ByVal idOrcamento As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Versao", DbType:="Int")> ByVal versao As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idOrcamento, versao)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AtualizaAprovacaoOrçamento")>  _
	Public Function AtualizaAprovacaoOrçamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrçamento", DbType:="Int")> ByVal idOrçamento As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Status", DbType:="Bit")> ByVal status As System.Nullable(Of Boolean), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataAprov", DbType:="Date")> ByVal dataAprov As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="HoraAprov", DbType:="Time")> ByVal horaAprov As System.Nullable(Of System.TimeSpan), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdTecAprov", DbType:="Int")> ByVal idTecAprov As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idOrçamento, status, dataAprov, horaAprov, idTecAprov)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AtualizaProdutoOrçamento")>  _
	Public Function AtualizaProdutoOrçamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdProduto", DbType:="Int")> ByVal idProduto As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdSolicitacao", DbType:="Int")> ByVal idSolicitacao As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idProduto, idSolicitacao)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AtualizaClienteOrcameto")>  _
	Public Function AtualizaClienteOrcameto(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Idorcamento", DbType:="Int")> ByVal idorcamento As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdCliente", DbType:="Int")> ByVal idCliente As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idorcamento, idCliente)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InsereNovoOrcamento")>  _
	Public Function InsereNovoOrcamento( _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdSolicitante", DbType:="Int")> ByVal idSolicitante As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdTecOrc", DbType:="Int")> ByVal idTecOrc As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataOrc", DbType:="Date")> ByVal dataOrc As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="HrOrc", DbType:="Time")> ByVal hrOrc As System.Nullable(Of System.TimeSpan),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataSol", DbType:="Date")> ByVal dataSol As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="HorSol", DbType:="Time")> ByVal horSol As System.Nullable(Of System.TimeSpan),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdCliente", DbType:="Int")> ByVal idCliente As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdVeiculo", DbType:="Int")> ByVal idVeiculo As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Aprovado", DbType:="Bit")> ByVal aprovado As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataAprov", DbType:="Date")> ByVal dataAprov As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="HrAprov", DbType:="Time")> ByVal hrAprov As System.Nullable(Of System.TimeSpan),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdTEcAprov", DbType:="Int")> ByVal idTEcAprov As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdDesmonte", DbType:="Int")> ByVal idDesmonte As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrcamentoIara", DbType:="Int")> ByVal idOrcamentoIara As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdCorOrcamentoExt", DbType:="Int")> ByVal idCorOrcamentoExt As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ValorRecebido", DbType:="Bit")> ByVal valorRecebido As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="NfEmitida", DbType:="Bit")> ByVal nfEmitida As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="NumNf", DbType:="Int")> ByVal numNf As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataNf", DbType:="Date")> ByVal dataNf As System.Nullable(Of Date)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idSolicitante, idTecOrc, dataOrc, hrOrc, dataSol, horSol, idCliente, idVeiculo, aprovado, dataAprov, hrAprov, idTEcAprov, idDesmonte, idOrcamentoIara, idCorOrcamentoExt, valorRecebido, nfEmitida, numNf, dataNf)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AtualizaValorRecebidoOrcamento")>  _
	Public Function AtualizaValorRecebidoOrcamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrçamento", DbType:="Int")> ByVal idOrçamento As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idOrçamento)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InsereNovoItemOrcamento")>  _
	Public Function InsereNovoItemOrcamento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdSolicitacao", DbType:="Int")> ByVal idSolicitacao As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdProduto", DbType:="Int")> ByVal idProduto As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdOrcamento", DbType:="Int")> ByVal idOrcamento As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Qtdade", DbType:="Money")> ByVal qtdade As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Versao", DbType:="Int")> ByVal versao As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ValorUnit", DbType:="Money")> ByVal valorUnit As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DescontoUnit", DbType:="Money")> ByVal descontoUnit As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataVersao", DbType:="Date")> ByVal dataVersao As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Tipo", DbType:="Bit")> ByVal tipo As System.Nullable(Of Boolean), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdSolucao", DbType:="Int")> ByVal idSolucao As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdImagemAval", DbType:="Int")> ByVal idImagemAval As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idSolicitacao, idProduto, idOrcamento, qtdade, versao, valorUnit, descontoUnit, dataVersao, tipo, idSolucao, idImagemAval)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.DeletaPedidoOnLine")>  _
	Public Function DeletaPedidoOnLine(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdPedidoOnLine", DbType:="Int")> ByVal idPedidoOnLine As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idPedidoOnLine)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AtualizaStatus1_PedidoOnLine")>  _
	Public Function AtualizaStatus1_PedidoOnLine(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdPedidoOnLine", DbType:="Int")> ByVal idPedidoOnLine As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Qtdade", DbType:="Bit")> ByVal qtdade As System.Nullable(Of Boolean), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Status_posicao", DbType:="Int")> ByVal status_posicao As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idPedidoOnLine, qtdade, status_posicao)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InserePedidoOnLine")>  _
	Public Function InserePedidoOnLine( _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdProdInt", DbType:="NText")> ByVal idProdInt As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdItemExterno", DbType:="Int")> ByVal idItemExterno As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ChaveFornecedor", DbType:="NText")> ByVal chaveFornecedor As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ChaveOficina", DbType:="NText")> ByVal chaveOficina As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataSol", DbType:="Date")> ByVal dataSol As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="HoraSol", DbType:="Time")> ByVal horaSol As System.Nullable(Of System.TimeSpan),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Cotado", DbType:="Bit")> ByVal cotado As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataCotacao", DbType:="Date")> ByVal dataCotacao As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdCotacao", DbType:="Int")> ByVal idCotacao As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ValidadoEstoque", DbType:="Bit")> ByVal validadoEstoque As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataValidadoEstoque", DbType:="Date")> ByVal dataValidadoEstoque As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdfunciValidadoe", DbType:="Int")> ByVal idfunciValidadoe As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="AprovadoFinanceiro", DbType:="Bit")> ByVal aprovadoFinanceiro As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataAprovadoFinanceiro", DbType:="Date")> ByVal dataAprovadoFinanceiro As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdFuncionarioAprovaFin", DbType:="Int")> ByVal idFuncionarioAprovaFin As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Separado", DbType:="Bit")> ByVal separado As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataSeparado", DbType:="Date")> ByVal dataSeparado As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdFuncionarioSeparado", DbType:="Int")> ByVal idFuncionarioSeparado As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Expedido", DbType:="Bit")> ByVal expedido As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataExpedido", DbType:="Date")> ByVal dataExpedido As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdFuncionarioExpedido", DbType:="Int")> ByVal idFuncionarioExpedido As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Entregue", DbType:="Bit")> ByVal entregue As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataEntregue", DbType:="Date")> ByVal dataEntregue As System.Nullable(Of Date),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ChaveEntregador", DbType:="NText")> ByVal chaveEntregador As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Qtdade", DbType:="Int")> ByVal qtdade As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VlrCompra", DbType:="Money")> ByVal vlrCompra As System.Nullable(Of Decimal),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VlrComissao", DbType:="Money")> ByVal vlrComissao As System.Nullable(Of Decimal),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VlrFrete", DbType:="Money")> ByVal vlrFrete As System.Nullable(Of Decimal),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Status_posicao", DbType:="Int")> ByVal status_posicao As System.Nullable(Of Integer),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdExternoPedido", DbType:="Int")> ByVal idExternoPedido As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idProdInt, idItemExterno, chaveFornecedor, chaveOficina, dataSol, horaSol, cotado, dataCotacao, idCotacao, validadoEstoque, dataValidadoEstoque, idfunciValidadoe, aprovadoFinanceiro, dataAprovadoFinanceiro, idFuncionarioAprovaFin, separado, dataSeparado, idFuncionarioSeparado, expedido, dataExpedido, idFuncionarioExpedido, entregue, dataEntregue, chaveEntregador, qtdade, vlrCompra, vlrComissao, vlrFrete, status_posicao, idExternoPedido)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AtualizaIdExterno_PedidoOnLine")>  _
	Public Function AtualizaIdExterno_PedidoOnLine(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdPedidoOnLine", DbType:="Int")> ByVal idPedidoOnLine As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdExternoPedido", DbType:="Int")> ByVal idExternoPedido As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idPedidoOnLine, idExternoPedido)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.FormasPGOrcamento")>  _
Partial Public Class FormasPGOrcamento
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdFormPgOrc As Integer
	
	Private _IdForma As System.Nullable(Of Integer)
	
	Private _IdOrcamento As System.Nullable(Of Integer)
	
	Private _IdVersao As System.Nullable(Of Integer)
	
	Private _Valor As System.Nullable(Of Decimal)
	
	Private _Pc As String
	
	Private _Vencimento As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdFormPgOrcChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdFormPgOrcChanged()
    End Sub
    Partial Private Sub OnIdFormaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdFormaChanged()
    End Sub
    Partial Private Sub OnIdOrcamentoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdOrcamentoChanged()
    End Sub
    Partial Private Sub OnIdVersaoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdVersaoChanged()
    End Sub
    Partial Private Sub OnValorChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnValorChanged()
    End Sub
    Partial Private Sub OnPcChanging(value As String)
    End Sub
    Partial Private Sub OnPcChanged()
    End Sub
    Partial Private Sub OnVencimentoChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnVencimentoChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdFormPgOrc", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdFormPgOrc() As Integer
		Get
			Return Me._IdFormPgOrc
		End Get
		Set
			If ((Me._IdFormPgOrc = value)  _
						= false) Then
				Me.OnIdFormPgOrcChanging(value)
				Me.SendPropertyChanging
				Me._IdFormPgOrc = value
				Me.SendPropertyChanged("IdFormPgOrc")
				Me.OnIdFormPgOrcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdForma", DbType:="Int")>  _
	Public Property IdForma() As System.Nullable(Of Integer)
		Get
			Return Me._IdForma
		End Get
		Set
			If (Me._IdForma.Equals(value) = false) Then
				Me.OnIdFormaChanging(value)
				Me.SendPropertyChanging
				Me._IdForma = value
				Me.SendPropertyChanged("IdForma")
				Me.OnIdFormaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdOrcamento", DbType:="Int")>  _
	Public Property IdOrcamento() As System.Nullable(Of Integer)
		Get
			Return Me._IdOrcamento
		End Get
		Set
			If (Me._IdOrcamento.Equals(value) = false) Then
				Me.OnIdOrcamentoChanging(value)
				Me.SendPropertyChanging
				Me._IdOrcamento = value
				Me.SendPropertyChanged("IdOrcamento")
				Me.OnIdOrcamentoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdVersao", DbType:="Int")>  _
	Public Property IdVersao() As System.Nullable(Of Integer)
		Get
			Return Me._IdVersao
		End Get
		Set
			If (Me._IdVersao.Equals(value) = false) Then
				Me.OnIdVersaoChanging(value)
				Me.SendPropertyChanging
				Me._IdVersao = value
				Me.SendPropertyChanged("IdVersao")
				Me.OnIdVersaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Valor", DbType:="Money")>  _
	Public Property Valor() As System.Nullable(Of Decimal)
		Get
			Return Me._Valor
		End Get
		Set
			If (Me._Valor.Equals(value) = false) Then
				Me.OnValorChanging(value)
				Me.SendPropertyChanging
				Me._Valor = value
				Me.SendPropertyChanged("Valor")
				Me.OnValorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Pc", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Pc() As String
		Get
			Return Me._Pc
		End Get
		Set
			If (String.Equals(Me._Pc, value) = false) Then
				Me.OnPcChanging(value)
				Me.SendPropertyChanging
				Me._Pc = value
				Me.SendPropertyChanged("Pc")
				Me.OnPcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Vencimento", DbType:="Date")>  _
	Public Property Vencimento() As System.Nullable(Of Date)
		Get
			Return Me._Vencimento
		End Get
		Set
			If (Me._Vencimento.Equals(value) = false) Then
				Me.OnVencimentoChanging(value)
				Me.SendPropertyChanging
				Me._Vencimento = value
				Me.SendPropertyChanged("Vencimento")
				Me.OnVencimentoChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Orcamentos")>  _
Partial Public Class Orcamentos
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdOrcamento As Integer
	
	Private _IdSolicitante As System.Nullable(Of Integer)
	
	Private _IdTecOrc As System.Nullable(Of Integer)
	
	Private _DataOrc As System.Nullable(Of Date)
	
	Private _HrOrc As System.Nullable(Of System.TimeSpan)
	
	Private _DataSol As System.Nullable(Of Date)
	
	Private _HorSol As System.Nullable(Of System.TimeSpan)
	
	Private _IdCliente As System.Nullable(Of Integer)
	
	Private _IdVeiculo As System.Nullable(Of Integer)
	
	Private _Aprovado As System.Nullable(Of Boolean)
	
	Private _DataAprov As System.Nullable(Of Date)
	
	Private _HrAprov As System.Nullable(Of System.TimeSpan)
	
	Private _IdTEcAprov As System.Nullable(Of Integer)
	
	Private _IdDesmonte As System.Nullable(Of Integer)
	
	Private _IdOrcamentoIara As System.Nullable(Of Integer)
	
	Private _IdCorOrcamentoExt As System.Nullable(Of Integer)
	
	Private _ValorRecebido As System.Nullable(Of Boolean)
	
	Private _NfEmitida As System.Nullable(Of Boolean)
	
	Private _NumNf As System.Nullable(Of Integer)
	
	Private _DataNf As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdOrcamentoChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdOrcamentoChanged()
    End Sub
    Partial Private Sub OnIdSolicitanteChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdSolicitanteChanged()
    End Sub
    Partial Private Sub OnIdTecOrcChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdTecOrcChanged()
    End Sub
    Partial Private Sub OnDataOrcChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataOrcChanged()
    End Sub
    Partial Private Sub OnHrOrcChanging(value As System.Nullable(Of System.TimeSpan))
    End Sub
    Partial Private Sub OnHrOrcChanged()
    End Sub
    Partial Private Sub OnDataSolChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataSolChanged()
    End Sub
    Partial Private Sub OnHorSolChanging(value As System.Nullable(Of System.TimeSpan))
    End Sub
    Partial Private Sub OnHorSolChanged()
    End Sub
    Partial Private Sub OnIdClienteChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdClienteChanged()
    End Sub
    Partial Private Sub OnIdVeiculoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdVeiculoChanged()
    End Sub
    Partial Private Sub OnAprovadoChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnAprovadoChanged()
    End Sub
    Partial Private Sub OnDataAprovChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataAprovChanged()
    End Sub
    Partial Private Sub OnHrAprovChanging(value As System.Nullable(Of System.TimeSpan))
    End Sub
    Partial Private Sub OnHrAprovChanged()
    End Sub
    Partial Private Sub OnIdTEcAprovChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdTEcAprovChanged()
    End Sub
    Partial Private Sub OnIdDesmonteChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdDesmonteChanged()
    End Sub
    Partial Private Sub OnIdOrcamentoIaraChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdOrcamentoIaraChanged()
    End Sub
    Partial Private Sub OnIdCorOrcamentoExtChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdCorOrcamentoExtChanged()
    End Sub
    Partial Private Sub OnValorRecebidoChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnValorRecebidoChanged()
    End Sub
    Partial Private Sub OnNfEmitidaChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnNfEmitidaChanged()
    End Sub
    Partial Private Sub OnNumNfChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnNumNfChanged()
    End Sub
    Partial Private Sub OnDataNfChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataNfChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdOrcamento", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdOrcamento() As Integer
		Get
			Return Me._IdOrcamento
		End Get
		Set
			If ((Me._IdOrcamento = value)  _
						= false) Then
				Me.OnIdOrcamentoChanging(value)
				Me.SendPropertyChanging
				Me._IdOrcamento = value
				Me.SendPropertyChanged("IdOrcamento")
				Me.OnIdOrcamentoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdSolicitante", DbType:="Int")>  _
	Public Property IdSolicitante() As System.Nullable(Of Integer)
		Get
			Return Me._IdSolicitante
		End Get
		Set
			If (Me._IdSolicitante.Equals(value) = false) Then
				Me.OnIdSolicitanteChanging(value)
				Me.SendPropertyChanging
				Me._IdSolicitante = value
				Me.SendPropertyChanged("IdSolicitante")
				Me.OnIdSolicitanteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdTecOrc", DbType:="Int")>  _
	Public Property IdTecOrc() As System.Nullable(Of Integer)
		Get
			Return Me._IdTecOrc
		End Get
		Set
			If (Me._IdTecOrc.Equals(value) = false) Then
				Me.OnIdTecOrcChanging(value)
				Me.SendPropertyChanging
				Me._IdTecOrc = value
				Me.SendPropertyChanged("IdTecOrc")
				Me.OnIdTecOrcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataOrc", DbType:="Date")>  _
	Public Property DataOrc() As System.Nullable(Of Date)
		Get
			Return Me._DataOrc
		End Get
		Set
			If (Me._DataOrc.Equals(value) = false) Then
				Me.OnDataOrcChanging(value)
				Me.SendPropertyChanging
				Me._DataOrc = value
				Me.SendPropertyChanged("DataOrc")
				Me.OnDataOrcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HrOrc", DbType:="Time")>  _
	Public Property HrOrc() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._HrOrc
		End Get
		Set
			If (Me._HrOrc.Equals(value) = false) Then
				Me.OnHrOrcChanging(value)
				Me.SendPropertyChanging
				Me._HrOrc = value
				Me.SendPropertyChanged("HrOrc")
				Me.OnHrOrcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataSol", DbType:="Date")>  _
	Public Property DataSol() As System.Nullable(Of Date)
		Get
			Return Me._DataSol
		End Get
		Set
			If (Me._DataSol.Equals(value) = false) Then
				Me.OnDataSolChanging(value)
				Me.SendPropertyChanging
				Me._DataSol = value
				Me.SendPropertyChanged("DataSol")
				Me.OnDataSolChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HorSol", DbType:="Time")>  _
	Public Property HorSol() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._HorSol
		End Get
		Set
			If (Me._HorSol.Equals(value) = false) Then
				Me.OnHorSolChanging(value)
				Me.SendPropertyChanging
				Me._HorSol = value
				Me.SendPropertyChanged("HorSol")
				Me.OnHorSolChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCliente", DbType:="Int")>  _
	Public Property IdCliente() As System.Nullable(Of Integer)
		Get
			Return Me._IdCliente
		End Get
		Set
			If (Me._IdCliente.Equals(value) = false) Then
				Me.OnIdClienteChanging(value)
				Me.SendPropertyChanging
				Me._IdCliente = value
				Me.SendPropertyChanged("IdCliente")
				Me.OnIdClienteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdVeiculo", DbType:="Int")>  _
	Public Property IdVeiculo() As System.Nullable(Of Integer)
		Get
			Return Me._IdVeiculo
		End Get
		Set
			If (Me._IdVeiculo.Equals(value) = false) Then
				Me.OnIdVeiculoChanging(value)
				Me.SendPropertyChanging
				Me._IdVeiculo = value
				Me.SendPropertyChanged("IdVeiculo")
				Me.OnIdVeiculoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Aprovado", DbType:="Bit")>  _
	Public Property Aprovado() As System.Nullable(Of Boolean)
		Get
			Return Me._Aprovado
		End Get
		Set
			If (Me._Aprovado.Equals(value) = false) Then
				Me.OnAprovadoChanging(value)
				Me.SendPropertyChanging
				Me._Aprovado = value
				Me.SendPropertyChanged("Aprovado")
				Me.OnAprovadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataAprov", DbType:="Date")>  _
	Public Property DataAprov() As System.Nullable(Of Date)
		Get
			Return Me._DataAprov
		End Get
		Set
			If (Me._DataAprov.Equals(value) = false) Then
				Me.OnDataAprovChanging(value)
				Me.SendPropertyChanging
				Me._DataAprov = value
				Me.SendPropertyChanged("DataAprov")
				Me.OnDataAprovChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HrAprov", DbType:="Time")>  _
	Public Property HrAprov() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._HrAprov
		End Get
		Set
			If (Me._HrAprov.Equals(value) = false) Then
				Me.OnHrAprovChanging(value)
				Me.SendPropertyChanging
				Me._HrAprov = value
				Me.SendPropertyChanged("HrAprov")
				Me.OnHrAprovChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdTEcAprov", DbType:="Int")>  _
	Public Property IdTEcAprov() As System.Nullable(Of Integer)
		Get
			Return Me._IdTEcAprov
		End Get
		Set
			If (Me._IdTEcAprov.Equals(value) = false) Then
				Me.OnIdTEcAprovChanging(value)
				Me.SendPropertyChanging
				Me._IdTEcAprov = value
				Me.SendPropertyChanged("IdTEcAprov")
				Me.OnIdTEcAprovChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdDesmonte", DbType:="Int")>  _
	Public Property IdDesmonte() As System.Nullable(Of Integer)
		Get
			Return Me._IdDesmonte
		End Get
		Set
			If (Me._IdDesmonte.Equals(value) = false) Then
				Me.OnIdDesmonteChanging(value)
				Me.SendPropertyChanging
				Me._IdDesmonte = value
				Me.SendPropertyChanged("IdDesmonte")
				Me.OnIdDesmonteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdOrcamentoIara", DbType:="Int")>  _
	Public Property IdOrcamentoIara() As System.Nullable(Of Integer)
		Get
			Return Me._IdOrcamentoIara
		End Get
		Set
			If (Me._IdOrcamentoIara.Equals(value) = false) Then
				Me.OnIdOrcamentoIaraChanging(value)
				Me.SendPropertyChanging
				Me._IdOrcamentoIara = value
				Me.SendPropertyChanged("IdOrcamentoIara")
				Me.OnIdOrcamentoIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCorOrcamentoExt", DbType:="Int")>  _
	Public Property IdCorOrcamentoExt() As System.Nullable(Of Integer)
		Get
			Return Me._IdCorOrcamentoExt
		End Get
		Set
			If (Me._IdCorOrcamentoExt.Equals(value) = false) Then
				Me.OnIdCorOrcamentoExtChanging(value)
				Me.SendPropertyChanging
				Me._IdCorOrcamentoExt = value
				Me.SendPropertyChanged("IdCorOrcamentoExt")
				Me.OnIdCorOrcamentoExtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValorRecebido", DbType:="Bit")>  _
	Public Property ValorRecebido() As System.Nullable(Of Boolean)
		Get
			Return Me._ValorRecebido
		End Get
		Set
			If (Me._ValorRecebido.Equals(value) = false) Then
				Me.OnValorRecebidoChanging(value)
				Me.SendPropertyChanging
				Me._ValorRecebido = value
				Me.SendPropertyChanged("ValorRecebido")
				Me.OnValorRecebidoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NfEmitida", DbType:="Bit")>  _
	Public Property NfEmitida() As System.Nullable(Of Boolean)
		Get
			Return Me._NfEmitida
		End Get
		Set
			If (Me._NfEmitida.Equals(value) = false) Then
				Me.OnNfEmitidaChanging(value)
				Me.SendPropertyChanging
				Me._NfEmitida = value
				Me.SendPropertyChanged("NfEmitida")
				Me.OnNfEmitidaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NumNf", DbType:="Int")>  _
	Public Property NumNf() As System.Nullable(Of Integer)
		Get
			Return Me._NumNf
		End Get
		Set
			If (Me._NumNf.Equals(value) = false) Then
				Me.OnNumNfChanging(value)
				Me.SendPropertyChanging
				Me._NumNf = value
				Me.SendPropertyChanged("NumNf")
				Me.OnNumNfChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataNf", DbType:="Date")>  _
	Public Property DataNf() As System.Nullable(Of Date)
		Get
			Return Me._DataNf
		End Get
		Set
			If (Me._DataNf.Equals(value) = false) Then
				Me.OnDataNfChanging(value)
				Me.SendPropertyChanging
				Me._DataNf = value
				Me.SendPropertyChanged("DataNf")
				Me.OnDataNfChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ProdutosOrcamento")>  _
Partial Public Class ProdutosOrcamento
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdProdutoOrcamento As Integer
	
	Private _IdSolicitacao As System.Nullable(Of Integer)
	
	Private _IdProduto As System.Nullable(Of Integer)
	
	Private _IdOrcamento As System.Nullable(Of Integer)
	
	Private _Qtdade As System.Nullable(Of Decimal)
	
	Private _ValorUnit As System.Nullable(Of Decimal)
	
	Private _DescontoUnit As System.Nullable(Of Decimal)
	
	Private _Versao As System.Nullable(Of Integer)
	
	Private _DataVersao As System.Nullable(Of Date)
	
	Private _Tipo As System.Nullable(Of Boolean)
	
	Private _IdSolucao As System.Nullable(Of Integer)
	
	Private _IdImagemAval As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdProdutoOrcamentoChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdProdutoOrcamentoChanged()
    End Sub
    Partial Private Sub OnIdSolicitacaoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdSolicitacaoChanged()
    End Sub
    Partial Private Sub OnIdProdutoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdProdutoChanged()
    End Sub
    Partial Private Sub OnIdOrcamentoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdOrcamentoChanged()
    End Sub
    Partial Private Sub OnQtdadeChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnQtdadeChanged()
    End Sub
    Partial Private Sub OnValorUnitChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnValorUnitChanged()
    End Sub
    Partial Private Sub OnDescontoUnitChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDescontoUnitChanged()
    End Sub
    Partial Private Sub OnVersaoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnVersaoChanged()
    End Sub
    Partial Private Sub OnDataVersaoChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataVersaoChanged()
    End Sub
    Partial Private Sub OnTipoChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnTipoChanged()
    End Sub
    Partial Private Sub OnIdSolucaoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdSolucaoChanged()
    End Sub
    Partial Private Sub OnIdImagemAvalChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdImagemAvalChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProdutoOrcamento", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdProdutoOrcamento() As Integer
		Get
			Return Me._IdProdutoOrcamento
		End Get
		Set
			If ((Me._IdProdutoOrcamento = value)  _
						= false) Then
				Me.OnIdProdutoOrcamentoChanging(value)
				Me.SendPropertyChanging
				Me._IdProdutoOrcamento = value
				Me.SendPropertyChanged("IdProdutoOrcamento")
				Me.OnIdProdutoOrcamentoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdSolicitacao", DbType:="Int")>  _
	Public Property IdSolicitacao() As System.Nullable(Of Integer)
		Get
			Return Me._IdSolicitacao
		End Get
		Set
			If (Me._IdSolicitacao.Equals(value) = false) Then
				Me.OnIdSolicitacaoChanging(value)
				Me.SendPropertyChanging
				Me._IdSolicitacao = value
				Me.SendPropertyChanged("IdSolicitacao")
				Me.OnIdSolicitacaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProduto", DbType:="Int")>  _
	Public Property IdProduto() As System.Nullable(Of Integer)
		Get
			Return Me._IdProduto
		End Get
		Set
			If (Me._IdProduto.Equals(value) = false) Then
				Me.OnIdProdutoChanging(value)
				Me.SendPropertyChanging
				Me._IdProduto = value
				Me.SendPropertyChanged("IdProduto")
				Me.OnIdProdutoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdOrcamento", DbType:="Int")>  _
	Public Property IdOrcamento() As System.Nullable(Of Integer)
		Get
			Return Me._IdOrcamento
		End Get
		Set
			If (Me._IdOrcamento.Equals(value) = false) Then
				Me.OnIdOrcamentoChanging(value)
				Me.SendPropertyChanging
				Me._IdOrcamento = value
				Me.SendPropertyChanged("IdOrcamento")
				Me.OnIdOrcamentoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Qtdade", DbType:="Money")>  _
	Public Property Qtdade() As System.Nullable(Of Decimal)
		Get
			Return Me._Qtdade
		End Get
		Set
			If (Me._Qtdade.Equals(value) = false) Then
				Me.OnQtdadeChanging(value)
				Me.SendPropertyChanging
				Me._Qtdade = value
				Me.SendPropertyChanged("Qtdade")
				Me.OnQtdadeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValorUnit", DbType:="Money")>  _
	Public Property ValorUnit() As System.Nullable(Of Decimal)
		Get
			Return Me._ValorUnit
		End Get
		Set
			If (Me._ValorUnit.Equals(value) = false) Then
				Me.OnValorUnitChanging(value)
				Me.SendPropertyChanging
				Me._ValorUnit = value
				Me.SendPropertyChanged("ValorUnit")
				Me.OnValorUnitChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DescontoUnit", DbType:="Money")>  _
	Public Property DescontoUnit() As System.Nullable(Of Decimal)
		Get
			Return Me._DescontoUnit
		End Get
		Set
			If (Me._DescontoUnit.Equals(value) = false) Then
				Me.OnDescontoUnitChanging(value)
				Me.SendPropertyChanging
				Me._DescontoUnit = value
				Me.SendPropertyChanged("DescontoUnit")
				Me.OnDescontoUnitChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Versao", DbType:="Int")>  _
	Public Property Versao() As System.Nullable(Of Integer)
		Get
			Return Me._Versao
		End Get
		Set
			If (Me._Versao.Equals(value) = false) Then
				Me.OnVersaoChanging(value)
				Me.SendPropertyChanging
				Me._Versao = value
				Me.SendPropertyChanged("Versao")
				Me.OnVersaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataVersao", DbType:="Date")>  _
	Public Property DataVersao() As System.Nullable(Of Date)
		Get
			Return Me._DataVersao
		End Get
		Set
			If (Me._DataVersao.Equals(value) = false) Then
				Me.OnDataVersaoChanging(value)
				Me.SendPropertyChanging
				Me._DataVersao = value
				Me.SendPropertyChanged("DataVersao")
				Me.OnDataVersaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Tipo", DbType:="Bit")>  _
	Public Property Tipo() As System.Nullable(Of Boolean)
		Get
			Return Me._Tipo
		End Get
		Set
			If (Me._Tipo.Equals(value) = false) Then
				Me.OnTipoChanging(value)
				Me.SendPropertyChanging
				Me._Tipo = value
				Me.SendPropertyChanged("Tipo")
				Me.OnTipoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdSolucao", DbType:="Int")>  _
	Public Property IdSolucao() As System.Nullable(Of Integer)
		Get
			Return Me._IdSolucao
		End Get
		Set
			If (Me._IdSolucao.Equals(value) = false) Then
				Me.OnIdSolucaoChanging(value)
				Me.SendPropertyChanging
				Me._IdSolucao = value
				Me.SendPropertyChanged("IdSolucao")
				Me.OnIdSolucaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdImagemAval", DbType:="Int")>  _
	Public Property IdImagemAval() As System.Nullable(Of Integer)
		Get
			Return Me._IdImagemAval
		End Get
		Set
			If (Me._IdImagemAval.Equals(value) = false) Then
				Me.OnIdImagemAvalChanging(value)
				Me.SendPropertyChanging
				Me._IdImagemAval = value
				Me.SendPropertyChanged("IdImagemAval")
				Me.OnIdImagemAvalChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.PedidoOnLine")>  _
Partial Public Class PedidoOnLine
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdPedidoOnLine As Integer
	
	Private _IdProdInt As String
	
	Private _IdItemExterno As System.Nullable(Of Integer)
	
	Private _ChaveFornecedor As String
	
	Private _ChaveOficina As String
	
	Private _DataSol As System.Nullable(Of Date)
	
	Private _HoraSol As System.Nullable(Of System.TimeSpan)
	
	Private _Cotado As System.Nullable(Of Boolean)
	
	Private _DataCotacao As System.Nullable(Of Date)
	
	Private _IdCotacao As System.Nullable(Of Integer)
	
	Private _ValidadoEstoque As System.Nullable(Of Boolean)
	
	Private _DataValidadoEstoque As System.Nullable(Of Date)
	
	Private _IdfunciValidadoe As System.Nullable(Of Integer)
	
	Private _AprovadoFinanceiro As System.Nullable(Of Boolean)
	
	Private _DataAprovadoFinanceiro As System.Nullable(Of Date)
	
	Private _IdFuncionarioAprovaFin As System.Nullable(Of Integer)
	
	Private _Separado As System.Nullable(Of Boolean)
	
	Private _DataSeparado As System.Nullable(Of Date)
	
	Private _IdFuncionarioSeparado As System.Nullable(Of Integer)
	
	Private _Expedido As System.Nullable(Of Boolean)
	
	Private _DataExpedido As System.Nullable(Of Date)
	
	Private _IdFuncionarioExpedido As System.Nullable(Of Integer)
	
	Private _Entregue As System.Nullable(Of Boolean)
	
	Private _DataEntregue As System.Nullable(Of Date)
	
	Private _ChaveEntregador As String
	
	Private _Qtdade As System.Nullable(Of Integer)
	
	Private _VlrCompra As System.Nullable(Of Decimal)
	
	Private _VlrComissao As System.Nullable(Of Decimal)
	
	Private _VlrFrete As System.Nullable(Of Decimal)
	
	Private _Status_posicao As System.Nullable(Of Integer)
	
	Private _IdExternoPedido As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdPedidoOnLineChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdPedidoOnLineChanged()
    End Sub
    Partial Private Sub OnIdProdIntChanging(value As String)
    End Sub
    Partial Private Sub OnIdProdIntChanged()
    End Sub
    Partial Private Sub OnIdItemExternoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdItemExternoChanged()
    End Sub
    Partial Private Sub OnChaveFornecedorChanging(value As String)
    End Sub
    Partial Private Sub OnChaveFornecedorChanged()
    End Sub
    Partial Private Sub OnChaveOficinaChanging(value As String)
    End Sub
    Partial Private Sub OnChaveOficinaChanged()
    End Sub
    Partial Private Sub OnDataSolChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataSolChanged()
    End Sub
    Partial Private Sub OnHoraSolChanging(value As System.Nullable(Of System.TimeSpan))
    End Sub
    Partial Private Sub OnHoraSolChanged()
    End Sub
    Partial Private Sub OnCotadoChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnCotadoChanged()
    End Sub
    Partial Private Sub OnDataCotacaoChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataCotacaoChanged()
    End Sub
    Partial Private Sub OnIdCotacaoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdCotacaoChanged()
    End Sub
    Partial Private Sub OnValidadoEstoqueChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnValidadoEstoqueChanged()
    End Sub
    Partial Private Sub OnDataValidadoEstoqueChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataValidadoEstoqueChanged()
    End Sub
    Partial Private Sub OnIdfunciValidadoeChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdfunciValidadoeChanged()
    End Sub
    Partial Private Sub OnAprovadoFinanceiroChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnAprovadoFinanceiroChanged()
    End Sub
    Partial Private Sub OnDataAprovadoFinanceiroChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataAprovadoFinanceiroChanged()
    End Sub
    Partial Private Sub OnIdFuncionarioAprovaFinChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdFuncionarioAprovaFinChanged()
    End Sub
    Partial Private Sub OnSeparadoChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnSeparadoChanged()
    End Sub
    Partial Private Sub OnDataSeparadoChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataSeparadoChanged()
    End Sub
    Partial Private Sub OnIdFuncionarioSeparadoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdFuncionarioSeparadoChanged()
    End Sub
    Partial Private Sub OnExpedidoChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnExpedidoChanged()
    End Sub
    Partial Private Sub OnDataExpedidoChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataExpedidoChanged()
    End Sub
    Partial Private Sub OnIdFuncionarioExpedidoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdFuncionarioExpedidoChanged()
    End Sub
    Partial Private Sub OnEntregueChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnEntregueChanged()
    End Sub
    Partial Private Sub OnDataEntregueChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataEntregueChanged()
    End Sub
    Partial Private Sub OnChaveEntregadorChanging(value As String)
    End Sub
    Partial Private Sub OnChaveEntregadorChanged()
    End Sub
    Partial Private Sub OnQtdadeChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnQtdadeChanged()
    End Sub
    Partial Private Sub OnVlrCompraChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVlrCompraChanged()
    End Sub
    Partial Private Sub OnVlrComissaoChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVlrComissaoChanged()
    End Sub
    Partial Private Sub OnVlrFreteChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVlrFreteChanged()
    End Sub
    Partial Private Sub OnStatus_posicaoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnStatus_posicaoChanged()
    End Sub
    Partial Private Sub OnIdExternoPedidoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdExternoPedidoChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdPedidoOnLine", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdPedidoOnLine() As Integer
		Get
			Return Me._IdPedidoOnLine
		End Get
		Set
			If ((Me._IdPedidoOnLine = value)  _
						= false) Then
				Me.OnIdPedidoOnLineChanging(value)
				Me.SendPropertyChanging
				Me._IdPedidoOnLine = value
				Me.SendPropertyChanged("IdPedidoOnLine")
				Me.OnIdPedidoOnLineChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProdInt", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property IdProdInt() As String
		Get
			Return Me._IdProdInt
		End Get
		Set
			If (String.Equals(Me._IdProdInt, value) = false) Then
				Me.OnIdProdIntChanging(value)
				Me.SendPropertyChanging
				Me._IdProdInt = value
				Me.SendPropertyChanged("IdProdInt")
				Me.OnIdProdIntChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdItemExterno", DbType:="Int")>  _
	Public Property IdItemExterno() As System.Nullable(Of Integer)
		Get
			Return Me._IdItemExterno
		End Get
		Set
			If (Me._IdItemExterno.Equals(value) = false) Then
				Me.OnIdItemExternoChanging(value)
				Me.SendPropertyChanging
				Me._IdItemExterno = value
				Me.SendPropertyChanged("IdItemExterno")
				Me.OnIdItemExternoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChaveFornecedor", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property ChaveFornecedor() As String
		Get
			Return Me._ChaveFornecedor
		End Get
		Set
			If (String.Equals(Me._ChaveFornecedor, value) = false) Then
				Me.OnChaveFornecedorChanging(value)
				Me.SendPropertyChanging
				Me._ChaveFornecedor = value
				Me.SendPropertyChanged("ChaveFornecedor")
				Me.OnChaveFornecedorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChaveOficina", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property ChaveOficina() As String
		Get
			Return Me._ChaveOficina
		End Get
		Set
			If (String.Equals(Me._ChaveOficina, value) = false) Then
				Me.OnChaveOficinaChanging(value)
				Me.SendPropertyChanging
				Me._ChaveOficina = value
				Me.SendPropertyChanged("ChaveOficina")
				Me.OnChaveOficinaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataSol", DbType:="Date")>  _
	Public Property DataSol() As System.Nullable(Of Date)
		Get
			Return Me._DataSol
		End Get
		Set
			If (Me._DataSol.Equals(value) = false) Then
				Me.OnDataSolChanging(value)
				Me.SendPropertyChanging
				Me._DataSol = value
				Me.SendPropertyChanged("DataSol")
				Me.OnDataSolChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HoraSol", DbType:="Time")>  _
	Public Property HoraSol() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._HoraSol
		End Get
		Set
			If (Me._HoraSol.Equals(value) = false) Then
				Me.OnHoraSolChanging(value)
				Me.SendPropertyChanging
				Me._HoraSol = value
				Me.SendPropertyChanged("HoraSol")
				Me.OnHoraSolChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cotado", DbType:="Bit")>  _
	Public Property Cotado() As System.Nullable(Of Boolean)
		Get
			Return Me._Cotado
		End Get
		Set
			If (Me._Cotado.Equals(value) = false) Then
				Me.OnCotadoChanging(value)
				Me.SendPropertyChanging
				Me._Cotado = value
				Me.SendPropertyChanged("Cotado")
				Me.OnCotadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataCotacao", DbType:="Date")>  _
	Public Property DataCotacao() As System.Nullable(Of Date)
		Get
			Return Me._DataCotacao
		End Get
		Set
			If (Me._DataCotacao.Equals(value) = false) Then
				Me.OnDataCotacaoChanging(value)
				Me.SendPropertyChanging
				Me._DataCotacao = value
				Me.SendPropertyChanged("DataCotacao")
				Me.OnDataCotacaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCotacao", DbType:="Int")>  _
	Public Property IdCotacao() As System.Nullable(Of Integer)
		Get
			Return Me._IdCotacao
		End Get
		Set
			If (Me._IdCotacao.Equals(value) = false) Then
				Me.OnIdCotacaoChanging(value)
				Me.SendPropertyChanging
				Me._IdCotacao = value
				Me.SendPropertyChanged("IdCotacao")
				Me.OnIdCotacaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValidadoEstoque", DbType:="Bit")>  _
	Public Property ValidadoEstoque() As System.Nullable(Of Boolean)
		Get
			Return Me._ValidadoEstoque
		End Get
		Set
			If (Me._ValidadoEstoque.Equals(value) = false) Then
				Me.OnValidadoEstoqueChanging(value)
				Me.SendPropertyChanging
				Me._ValidadoEstoque = value
				Me.SendPropertyChanged("ValidadoEstoque")
				Me.OnValidadoEstoqueChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataValidadoEstoque", DbType:="Date")>  _
	Public Property DataValidadoEstoque() As System.Nullable(Of Date)
		Get
			Return Me._DataValidadoEstoque
		End Get
		Set
			If (Me._DataValidadoEstoque.Equals(value) = false) Then
				Me.OnDataValidadoEstoqueChanging(value)
				Me.SendPropertyChanging
				Me._DataValidadoEstoque = value
				Me.SendPropertyChanged("DataValidadoEstoque")
				Me.OnDataValidadoEstoqueChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdfunciValidadoe", DbType:="Int")>  _
	Public Property IdfunciValidadoe() As System.Nullable(Of Integer)
		Get
			Return Me._IdfunciValidadoe
		End Get
		Set
			If (Me._IdfunciValidadoe.Equals(value) = false) Then
				Me.OnIdfunciValidadoeChanging(value)
				Me.SendPropertyChanging
				Me._IdfunciValidadoe = value
				Me.SendPropertyChanged("IdfunciValidadoe")
				Me.OnIdfunciValidadoeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AprovadoFinanceiro", DbType:="Bit")>  _
	Public Property AprovadoFinanceiro() As System.Nullable(Of Boolean)
		Get
			Return Me._AprovadoFinanceiro
		End Get
		Set
			If (Me._AprovadoFinanceiro.Equals(value) = false) Then
				Me.OnAprovadoFinanceiroChanging(value)
				Me.SendPropertyChanging
				Me._AprovadoFinanceiro = value
				Me.SendPropertyChanged("AprovadoFinanceiro")
				Me.OnAprovadoFinanceiroChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataAprovadoFinanceiro", DbType:="Date")>  _
	Public Property DataAprovadoFinanceiro() As System.Nullable(Of Date)
		Get
			Return Me._DataAprovadoFinanceiro
		End Get
		Set
			If (Me._DataAprovadoFinanceiro.Equals(value) = false) Then
				Me.OnDataAprovadoFinanceiroChanging(value)
				Me.SendPropertyChanging
				Me._DataAprovadoFinanceiro = value
				Me.SendPropertyChanged("DataAprovadoFinanceiro")
				Me.OnDataAprovadoFinanceiroChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdFuncionarioAprovaFin", DbType:="Int")>  _
	Public Property IdFuncionarioAprovaFin() As System.Nullable(Of Integer)
		Get
			Return Me._IdFuncionarioAprovaFin
		End Get
		Set
			If (Me._IdFuncionarioAprovaFin.Equals(value) = false) Then
				Me.OnIdFuncionarioAprovaFinChanging(value)
				Me.SendPropertyChanging
				Me._IdFuncionarioAprovaFin = value
				Me.SendPropertyChanged("IdFuncionarioAprovaFin")
				Me.OnIdFuncionarioAprovaFinChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Separado", DbType:="Bit")>  _
	Public Property Separado() As System.Nullable(Of Boolean)
		Get
			Return Me._Separado
		End Get
		Set
			If (Me._Separado.Equals(value) = false) Then
				Me.OnSeparadoChanging(value)
				Me.SendPropertyChanging
				Me._Separado = value
				Me.SendPropertyChanged("Separado")
				Me.OnSeparadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataSeparado", DbType:="Date")>  _
	Public Property DataSeparado() As System.Nullable(Of Date)
		Get
			Return Me._DataSeparado
		End Get
		Set
			If (Me._DataSeparado.Equals(value) = false) Then
				Me.OnDataSeparadoChanging(value)
				Me.SendPropertyChanging
				Me._DataSeparado = value
				Me.SendPropertyChanged("DataSeparado")
				Me.OnDataSeparadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdFuncionarioSeparado", DbType:="Int")>  _
	Public Property IdFuncionarioSeparado() As System.Nullable(Of Integer)
		Get
			Return Me._IdFuncionarioSeparado
		End Get
		Set
			If (Me._IdFuncionarioSeparado.Equals(value) = false) Then
				Me.OnIdFuncionarioSeparadoChanging(value)
				Me.SendPropertyChanging
				Me._IdFuncionarioSeparado = value
				Me.SendPropertyChanged("IdFuncionarioSeparado")
				Me.OnIdFuncionarioSeparadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Expedido", DbType:="Bit")>  _
	Public Property Expedido() As System.Nullable(Of Boolean)
		Get
			Return Me._Expedido
		End Get
		Set
			If (Me._Expedido.Equals(value) = false) Then
				Me.OnExpedidoChanging(value)
				Me.SendPropertyChanging
				Me._Expedido = value
				Me.SendPropertyChanged("Expedido")
				Me.OnExpedidoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataExpedido", DbType:="Date")>  _
	Public Property DataExpedido() As System.Nullable(Of Date)
		Get
			Return Me._DataExpedido
		End Get
		Set
			If (Me._DataExpedido.Equals(value) = false) Then
				Me.OnDataExpedidoChanging(value)
				Me.SendPropertyChanging
				Me._DataExpedido = value
				Me.SendPropertyChanged("DataExpedido")
				Me.OnDataExpedidoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdFuncionarioExpedido", DbType:="Int")>  _
	Public Property IdFuncionarioExpedido() As System.Nullable(Of Integer)
		Get
			Return Me._IdFuncionarioExpedido
		End Get
		Set
			If (Me._IdFuncionarioExpedido.Equals(value) = false) Then
				Me.OnIdFuncionarioExpedidoChanging(value)
				Me.SendPropertyChanging
				Me._IdFuncionarioExpedido = value
				Me.SendPropertyChanged("IdFuncionarioExpedido")
				Me.OnIdFuncionarioExpedidoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Entregue", DbType:="Bit")>  _
	Public Property Entregue() As System.Nullable(Of Boolean)
		Get
			Return Me._Entregue
		End Get
		Set
			If (Me._Entregue.Equals(value) = false) Then
				Me.OnEntregueChanging(value)
				Me.SendPropertyChanging
				Me._Entregue = value
				Me.SendPropertyChanged("Entregue")
				Me.OnEntregueChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataEntregue", DbType:="Date")>  _
	Public Property DataEntregue() As System.Nullable(Of Date)
		Get
			Return Me._DataEntregue
		End Get
		Set
			If (Me._DataEntregue.Equals(value) = false) Then
				Me.OnDataEntregueChanging(value)
				Me.SendPropertyChanging
				Me._DataEntregue = value
				Me.SendPropertyChanged("DataEntregue")
				Me.OnDataEntregueChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChaveEntregador", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property ChaveEntregador() As String
		Get
			Return Me._ChaveEntregador
		End Get
		Set
			If (String.Equals(Me._ChaveEntregador, value) = false) Then
				Me.OnChaveEntregadorChanging(value)
				Me.SendPropertyChanging
				Me._ChaveEntregador = value
				Me.SendPropertyChanged("ChaveEntregador")
				Me.OnChaveEntregadorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Qtdade", DbType:="Int")>  _
	Public Property Qtdade() As System.Nullable(Of Integer)
		Get
			Return Me._Qtdade
		End Get
		Set
			If (Me._Qtdade.Equals(value) = false) Then
				Me.OnQtdadeChanging(value)
				Me.SendPropertyChanging
				Me._Qtdade = value
				Me.SendPropertyChanged("Qtdade")
				Me.OnQtdadeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VlrCompra", DbType:="Money")>  _
	Public Property VlrCompra() As System.Nullable(Of Decimal)
		Get
			Return Me._VlrCompra
		End Get
		Set
			If (Me._VlrCompra.Equals(value) = false) Then
				Me.OnVlrCompraChanging(value)
				Me.SendPropertyChanging
				Me._VlrCompra = value
				Me.SendPropertyChanged("VlrCompra")
				Me.OnVlrCompraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VlrComissao", DbType:="Money")>  _
	Public Property VlrComissao() As System.Nullable(Of Decimal)
		Get
			Return Me._VlrComissao
		End Get
		Set
			If (Me._VlrComissao.Equals(value) = false) Then
				Me.OnVlrComissaoChanging(value)
				Me.SendPropertyChanging
				Me._VlrComissao = value
				Me.SendPropertyChanged("VlrComissao")
				Me.OnVlrComissaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VlrFrete", DbType:="Money")>  _
	Public Property VlrFrete() As System.Nullable(Of Decimal)
		Get
			Return Me._VlrFrete
		End Get
		Set
			If (Me._VlrFrete.Equals(value) = false) Then
				Me.OnVlrFreteChanging(value)
				Me.SendPropertyChanging
				Me._VlrFrete = value
				Me.SendPropertyChanged("VlrFrete")
				Me.OnVlrFreteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status_posicao", DbType:="Int")>  _
	Public Property Status_posicao() As System.Nullable(Of Integer)
		Get
			Return Me._Status_posicao
		End Get
		Set
			If (Me._Status_posicao.Equals(value) = false) Then
				Me.OnStatus_posicaoChanging(value)
				Me.SendPropertyChanging
				Me._Status_posicao = value
				Me.SendPropertyChanged("Status_posicao")
				Me.OnStatus_posicaoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdExternoPedido", DbType:="Int")>  _
	Public Property IdExternoPedido() As System.Nullable(Of Integer)
		Get
			Return Me._IdExternoPedido
		End Get
		Set
			If (Me._IdExternoPedido.Equals(value) = false) Then
				Me.OnIdExternoPedidoChanging(value)
				Me.SendPropertyChanging
				Me._IdExternoPedido = value
				Me.SendPropertyChanged("IdExternoPedido")
				Me.OnIdExternoPedidoChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
