'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidade de salvamento automático do My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Base;User ID=sqlsystem;Password=1q2w3e4r*")>
        Public ReadOnly Property BaseConnectionString() As String
            Get
                Return CType(Me("BaseConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Oficina;Persist Security Info=True;User ID=sq" &
            "lsystem;Password=1q2w3e4r*")>
        Public ReadOnly Property OficinaConnectionString() As String
            Get
                Return CType(Me("OficinaConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=TransportePrestadorOnLine;Persist Security In" &
            "fo=True;User ID=sqlsystem;Password=1q2w3e4r*")>
        Public ReadOnly Property TransportePrestadorOnLineConnectionString() As String
            Get
                Return CType(Me("TransportePrestadorOnLineConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Jarbes;Persist Security Info=True;User ID=sql" &
            "system;Password=1q2w3e4r*")>
        Public ReadOnly Property JarbesConnectionString() As String
            Get
                Return CType(Me("JarbesConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=TransportePrestadorOnLine;Persist Security In" &
            "fo=True;User ID=sqlsystem;Password=1q2w3e4r*")>
        Public ReadOnly Property TransportePrestadorOnLineConnectionString1() As String
            Get
                Return CType(Me("TransportePrestadorOnLineConnectionString1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Comercial;User ID=sqlsystem;Password=1q2w3e4r" &
            "*")>
        Public ReadOnly Property ComercialConnectionString() As String
            Get
                Return CType(Me("ComercialConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Financeiro;Persist Security Info=True;User ID" &
            "=SqlSystem;Password=1q2w3e4r*")>
        Public ReadOnly Property FinanceiroConnectionString() As String
            Get
                Return CType(Me("FinanceiroConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=EstoqueDistribuidorOnLine;Persist Security In" &
            "fo=True;User ID=sqlsystem")>
        Public ReadOnly Property EstoqueDistribuidorOnLineConnectionString() As String
            Get
                Return CType(Me("EstoqueDistribuidorOnLineConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Base;Persist Security Info=True;User ID=sqlsy" &
            "stem;Password=1q2w3e4r*")>
        Public ReadOnly Property BaseConnectionString1() As String
            Get
                Return CType(Me("BaseConnectionString1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=IARA;Persist Security Info=True;User ID=SqlSy" &
            "stem;Password=1q2w3e4r*")>
        Public ReadOnly Property IARAConnectionString() As String
            Get
                Return CType(Me("IARAConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Comercial;Persist Security Info=True;User ID=" &
            "sqlsystem;Password=1q2w3e4r*")>
        Public ReadOnly Property ComercialConnectionString1() As String
            Get
                Return CType(Me("ComercialConnectionString1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=EstoqueLocal;Persist Security Info=True;User " &
            "ID=SqlSystem;Password=1q2w3e4r*")>
        Public ReadOnly Property EstoqueLocalConnectionString() As String
            Get
                Return CType(Me("EstoqueLocalConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=0.0.0.0;Initial Catalog=Oficina;Persist Security Info=True;User ID=sq" &
            "lsystem;Password=1q2w3e4r*")>
        Public ReadOnly Property OficinaConnectionString1() As String
            Get
                Return CType(Me("OficinaConnectionString1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AMI-NOTEBOOK;Initial Catalog=Base;Persist Security Info=True;User ID=" &
            "sqlsystem")>
        Public ReadOnly Property BaseConnectionString2() As String
            Get
                Return CType(Me("BaseConnectionString2"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AMI-NOTEBOOK;Initial Catalog=Oficina;Persist Security Info=True;User " &
            "ID=SqlSystem")>
        Public ReadOnly Property OficinaConnectionString2() As String
            Get
                Return CType(Me("OficinaConnectionString2"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.7;Initial Catalog=TransportePrestadorOnline;Persist Securit" &
            "y Info=True;User ID=SqlSystem")>
        Public ReadOnly Property TransportePrestadorOnlineConnectionString2() As String
            Get
                Return CType(Me("TransportePrestadorOnlineConnectionString2"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AMI-NOTEBOOK;Initial Catalog=Comercial;Persist Security Info=True;Use" &
            "r ID=SqlSystem")>
        Public ReadOnly Property ComercialConnectionString2() As String
            Get
                Return CType(Me("ComercialConnectionString2"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AMI-NOTEBOOK;Initial Catalog=Financeiro;Persist Security Info=True;Us" &
            "er ID=SqlSystem")>
        Public ReadOnly Property FinanceiroConnectionString1() As String
            Get
                Return CType(Me("FinanceiroConnectionString1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AMI-NOTEBOOK;Initial Catalog=EstoqueLocal;Persist Security Info=True;" &
            "User ID=SqlSystem")>
        Public ReadOnly Property EstoqueLocalConnectionString1() As String
            Get
                Return CType(Me("EstoqueLocalConnectionString1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=AMI-NOTEBOOK;Initial Catalog=EstoqueDistribuidorOnLine;Persist Securi" &
            "ty Info=True;User ID=sqlsystem")>
        Public ReadOnly Property EstoqueDistribuidorOnLineConnectionString1() As String
            Get
                Return CType(Me("EstoqueDistribuidorOnLineConnectionString1"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=""152.254.236.69\sqlexpress, 14333"";Initial Catalog=EstoqueDistribuido" &
            "rOnLine;Persist Security Info=True;User ID=sqlsystem")>
        Public ReadOnly Property EstoqueDistribuidorOnLineConnectionString2() As String
            Get
                Return CType(Me("EstoqueDistribuidorOnLineConnectionString2"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-K3M64OB;Initial Catalog=Oficina;Persist Security Info=True;Us" &
            "er ID=sqlsystem")>
        Public ReadOnly Property OficinaConnectionString3() As String
            Get
                Return CType(Me("OficinaConnectionString3"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-K3M64OB;Initial Catalog=Comercial;Persist Security Info=True;" &
            "User ID=SqlSystem")>
        Public ReadOnly Property ComercialConnectionString3() As String
            Get
                Return CType(Me("ComercialConnectionString3"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-K3M64OB;Initial Catalog=Base;Persist Security Info=True;User " &
            "ID=SqlSystem")>
        Public ReadOnly Property BaseConnectionString3() As String
            Get
                Return CType(Me("BaseConnectionString3"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-K3M64OB;Initial Catalog=EstoqueLocal;Persist Security Info=Tr" &
            "ue;User ID=Sqlsystem")>
        Public ReadOnly Property EstoqueLocalConnectionString2() As String
            Get
                Return CType(Me("EstoqueLocalConnectionString2"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-K3M64OB;Initial Catalog=Financeiro;Persist Security Info=True" &
            ";User ID=SqlSystem")>
        Public ReadOnly Property FinanceiroConnectionString2() As String
            Get
                Return CType(Me("FinanceiroConnectionString2"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-K3M64OB;Initial Catalog=Trabalhista;Persist Security Info=Tru" &
            "e;User ID=SqlSystem")>
        Public ReadOnly Property TrabalhistaConnectionString() As String
            Get
                Return CType(Me("TrabalhistaConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("endereco_ambiente_acessar_envio")>
        Public ReadOnly Property CRM_BASE_WebReference_ServicoEnviarLoteEventos() As String
            Get
                Return CType(Me("CRM_BASE_WebReference_ServicoEnviarLoteEventos"), String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CRM_BASE.My.MySettings
            Get
                Return Global.CRM_BASE.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
