'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="IARA")>  _
Partial Public Class LqIaraDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertChavesIara(instance As ChavesIara)
    End Sub
  Partial Private Sub UpdateChavesIara(instance As ChavesIara)
    End Sub
  Partial Private Sub DeleteChavesIara(instance As ChavesIara)
    End Sub
  Partial Private Sub InsertClientesJv(instance As ClientesJv)
    End Sub
  Partial Private Sub UpdateClientesJv(instance As ClientesJv)
    End Sub
  Partial Private Sub DeleteClientesJv(instance As ClientesJv)
    End Sub
  Partial Private Sub InsertProdutosJV(instance As ProdutosJV)
    End Sub
  Partial Private Sub UpdateProdutosJV(instance As ProdutosJV)
    End Sub
  Partial Private Sub DeleteProdutosJV(instance As ProdutosJV)
    End Sub
  Partial Private Sub InsertLicensasIara(instance As LicensasIara)
    End Sub
  Partial Private Sub UpdateLicensasIara(instance As LicensasIara)
    End Sub
  Partial Private Sub DeleteLicensasIara(instance As LicensasIara)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Instalador_IARA.My.MySettings.Default.IARAConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property ChavesIara() As System.Data.Linq.Table(Of ChavesIara)
		Get
			Return Me.GetTable(Of ChavesIara)
		End Get
	End Property
	
	Public ReadOnly Property ClientesJv() As System.Data.Linq.Table(Of ClientesJv)
		Get
			Return Me.GetTable(Of ClientesJv)
		End Get
	End Property
	
	Public ReadOnly Property ProdutosJV() As System.Data.Linq.Table(Of ProdutosJV)
		Get
			Return Me.GetTable(Of ProdutosJV)
		End Get
	End Property
	
	Public ReadOnly Property LicensasIara() As System.Data.Linq.Table(Of LicensasIara)
		Get
			Return Me.GetTable(Of LicensasIara)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InsereNovaChaveIara")>  _
	Public Function InsereNovaChaveIara(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdClienteIara", DbType:="Int")> ByVal idClienteIara As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdProdutoIara", DbType:="Int")> ByVal idProdutoIara As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="NumeroDaChaveIara", DbType:="NText")> ByVal numeroDaChaveIara As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ValidadeDiasIara", DbType:="Int")> ByVal validadeDiasIara As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataLiberacaoIara", DbType:="Date")> ByVal dataLiberacaoIara As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="HoraLiberacaoIara", DbType:="Time")> ByVal horaLiberacaoIara As System.Nullable(Of System.TimeSpan), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DataAtivacaoIara", DbType:="Date")> ByVal dataAtivacaoIara As System.Nullable(Of Date), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="HoraAtivacaoIara", DbType:="Time")> ByVal horaAtivacaoIara As System.Nullable(Of System.TimeSpan), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IpAtivacaoIara", DbType:="NText")> ByVal ipAtivacaoIara As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Status", DbType:="Bit")> ByVal status As System.Nullable(Of Boolean)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idClienteIara, idProdutoIara, numeroDaChaveIara, validadeDiasIara, dataLiberacaoIara, horaLiberacaoIara, dataAtivacaoIara, horaAtivacaoIara, ipAtivacaoIara, status)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InsereNovoClienteIara")>  _
	Public Function InsereNovoClienteIara( _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="NomeCompletoJv", DbType:="NText")> ByVal nomeCompletoJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TipoDocJv", DbType:="Bit")> ByVal tipoDocJv As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DOCJv", DbType:="NText")> ByVal dOCJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="RG_IEJv", DbType:="NText")> ByVal rG_IEJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="EnderecoJv", DbType:="NText")> ByVal enderecoJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="BairroJv", DbType:="NText")> ByVal bairroJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CidadeJv", DbType:="NText")> ByVal cidadeJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="EstadoJv", DbType:="NText")> ByVal estadoJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="PaisJv", DbType:="NText")> ByVal paisJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CEpJv", DbType:="NText")> ByVal cEpJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NText")> ByVal telefoneJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CelularJv", DbType:="NText")> ByVal celularJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="WhattsappJv", DbType:="Bit")> ByVal whattsappJv As System.Nullable(Of Boolean),  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ContatoJv", DbType:="NText")> ByVal contatoJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NText")> ByVal celularContatoJv As String,  _
				<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="EmailJv", DbType:="NText")> ByVal emailJv As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), nomeCompletoJv, tipoDocJv, dOCJv, rG_IEJv, enderecoJv, bairroJv, cidadeJv, estadoJv, paisJv, cEpJv, telefoneJv, celularJv, whattsappJv, contatoJv, celularContatoJv, emailJv)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InsereNovaLicensaChaveIara")>  _
	Public Function InsereNovaLicensaChaveIara(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdChaveIara", DbType:="Int")> ByVal idChaveIara As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DispositivoClienteIara", DbType:="NText")> ByVal dispositivoClienteIara As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TipoLicensaIara", DbType:="Bit")> ByVal tipoLicensaIara As System.Nullable(Of Boolean), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="MACAdressIara", DbType:="NText")> ByVal mACAdressIara As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IpInt", DbType:="NText")> ByVal ipInt As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IpExt", DbType:="NText")> ByVal ipExt As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdCliente", DbType:="Int")> ByVal idCliente As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NText")> ByVal modulo As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idChaveIara, dispositivoClienteIara, tipoLicensaIara, mACAdressIara, ipInt, ipExt, idCliente, modulo)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ChavesIara")>  _
Partial Public Class ChavesIara
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdChaveIara As Integer
	
	Private _IdClienteIara As System.Nullable(Of Integer)
	
	Private _IdProdutoIara As System.Nullable(Of Integer)
	
	Private _NumeroDaChaveIara As String
	
	Private _ValidadeDiasIara As System.Nullable(Of Integer)
	
	Private _DataLiberacaoIara As System.Nullable(Of Date)
	
	Private _HoraLiberacaoIara As System.Nullable(Of System.TimeSpan)
	
	Private _DataAtivacaoIara As System.Nullable(Of Date)
	
	Private _HoraAtivacaoIara As System.Nullable(Of System.TimeSpan)
	
	Private _IpAtivacaoIara As String
	
	Private _Status As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdChaveIaraChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdChaveIaraChanged()
    End Sub
    Partial Private Sub OnIdClienteIaraChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdClienteIaraChanged()
    End Sub
    Partial Private Sub OnIdProdutoIaraChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdProdutoIaraChanged()
    End Sub
    Partial Private Sub OnNumeroDaChaveIaraChanging(value As String)
    End Sub
    Partial Private Sub OnNumeroDaChaveIaraChanged()
    End Sub
    Partial Private Sub OnValidadeDiasIaraChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnValidadeDiasIaraChanged()
    End Sub
    Partial Private Sub OnDataLiberacaoIaraChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataLiberacaoIaraChanged()
    End Sub
    Partial Private Sub OnHoraLiberacaoIaraChanging(value As System.Nullable(Of System.TimeSpan))
    End Sub
    Partial Private Sub OnHoraLiberacaoIaraChanged()
    End Sub
    Partial Private Sub OnDataAtivacaoIaraChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataAtivacaoIaraChanged()
    End Sub
    Partial Private Sub OnHoraAtivacaoIaraChanging(value As System.Nullable(Of System.TimeSpan))
    End Sub
    Partial Private Sub OnHoraAtivacaoIaraChanged()
    End Sub
    Partial Private Sub OnIpAtivacaoIaraChanging(value As String)
    End Sub
    Partial Private Sub OnIpAtivacaoIaraChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdChaveIara", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdChaveIara() As Integer
		Get
			Return Me._IdChaveIara
		End Get
		Set
			If ((Me._IdChaveIara = value)  _
						= false) Then
				Me.OnIdChaveIaraChanging(value)
				Me.SendPropertyChanging
				Me._IdChaveIara = value
				Me.SendPropertyChanged("IdChaveIara")
				Me.OnIdChaveIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdClienteIara", DbType:="Int")>  _
	Public Property IdClienteIara() As System.Nullable(Of Integer)
		Get
			Return Me._IdClienteIara
		End Get
		Set
			If (Me._IdClienteIara.Equals(value) = false) Then
				Me.OnIdClienteIaraChanging(value)
				Me.SendPropertyChanging
				Me._IdClienteIara = value
				Me.SendPropertyChanged("IdClienteIara")
				Me.OnIdClienteIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProdutoIara", DbType:="Int")>  _
	Public Property IdProdutoIara() As System.Nullable(Of Integer)
		Get
			Return Me._IdProdutoIara
		End Get
		Set
			If (Me._IdProdutoIara.Equals(value) = false) Then
				Me.OnIdProdutoIaraChanging(value)
				Me.SendPropertyChanging
				Me._IdProdutoIara = value
				Me.SendPropertyChanged("IdProdutoIara")
				Me.OnIdProdutoIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NumeroDaChaveIara", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property NumeroDaChaveIara() As String
		Get
			Return Me._NumeroDaChaveIara
		End Get
		Set
			If (String.Equals(Me._NumeroDaChaveIara, value) = false) Then
				Me.OnNumeroDaChaveIaraChanging(value)
				Me.SendPropertyChanging
				Me._NumeroDaChaveIara = value
				Me.SendPropertyChanged("NumeroDaChaveIara")
				Me.OnNumeroDaChaveIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValidadeDiasIara", DbType:="Int")>  _
	Public Property ValidadeDiasIara() As System.Nullable(Of Integer)
		Get
			Return Me._ValidadeDiasIara
		End Get
		Set
			If (Me._ValidadeDiasIara.Equals(value) = false) Then
				Me.OnValidadeDiasIaraChanging(value)
				Me.SendPropertyChanging
				Me._ValidadeDiasIara = value
				Me.SendPropertyChanged("ValidadeDiasIara")
				Me.OnValidadeDiasIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataLiberacaoIara", DbType:="Date")>  _
	Public Property DataLiberacaoIara() As System.Nullable(Of Date)
		Get
			Return Me._DataLiberacaoIara
		End Get
		Set
			If (Me._DataLiberacaoIara.Equals(value) = false) Then
				Me.OnDataLiberacaoIaraChanging(value)
				Me.SendPropertyChanging
				Me._DataLiberacaoIara = value
				Me.SendPropertyChanged("DataLiberacaoIara")
				Me.OnDataLiberacaoIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HoraLiberacaoIara", DbType:="Time")>  _
	Public Property HoraLiberacaoIara() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._HoraLiberacaoIara
		End Get
		Set
			If (Me._HoraLiberacaoIara.Equals(value) = false) Then
				Me.OnHoraLiberacaoIaraChanging(value)
				Me.SendPropertyChanging
				Me._HoraLiberacaoIara = value
				Me.SendPropertyChanged("HoraLiberacaoIara")
				Me.OnHoraLiberacaoIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataAtivacaoIara", DbType:="Date")>  _
	Public Property DataAtivacaoIara() As System.Nullable(Of Date)
		Get
			Return Me._DataAtivacaoIara
		End Get
		Set
			If (Me._DataAtivacaoIara.Equals(value) = false) Then
				Me.OnDataAtivacaoIaraChanging(value)
				Me.SendPropertyChanging
				Me._DataAtivacaoIara = value
				Me.SendPropertyChanged("DataAtivacaoIara")
				Me.OnDataAtivacaoIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HoraAtivacaoIara", DbType:="Time")>  _
	Public Property HoraAtivacaoIara() As System.Nullable(Of System.TimeSpan)
		Get
			Return Me._HoraAtivacaoIara
		End Get
		Set
			If (Me._HoraAtivacaoIara.Equals(value) = false) Then
				Me.OnHoraAtivacaoIaraChanging(value)
				Me.SendPropertyChanging
				Me._HoraAtivacaoIara = value
				Me.SendPropertyChanged("HoraAtivacaoIara")
				Me.OnHoraAtivacaoIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IpAtivacaoIara", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property IpAtivacaoIara() As String
		Get
			Return Me._IpAtivacaoIara
		End Get
		Set
			If (String.Equals(Me._IpAtivacaoIara, value) = false) Then
				Me.OnIpAtivacaoIaraChanging(value)
				Me.SendPropertyChanging
				Me._IpAtivacaoIara = value
				Me.SendPropertyChanged("IpAtivacaoIara")
				Me.OnIpAtivacaoIaraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="Bit")>  _
	Public Property Status() As System.Nullable(Of Boolean)
		Get
			Return Me._Status
		End Get
		Set
			If (Me._Status.Equals(value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ClientesJv")>  _
Partial Public Class ClientesJv
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdClienteJv As Integer
	
	Private _NomeCompletoJv As String
	
	Private _TipoDocJv As System.Nullable(Of Boolean)
	
	Private _DOCJv As String
	
	Private _RG_IEJv As String
	
	Private _EnderecoJv As String
	
	Private _BairroJv As String
	
	Private _CidadeJv As String
	
	Private _EstadoJv As String
	
	Private _PaisJv As String
	
	Private _CepJv As String
	
	Private _TelefoneJv As String
	
	Private _CelularJv As String
	
	Private _WhattsappJv As System.Nullable(Of Boolean)
	
	Private _ContatoJv As String
	
	Private _CelularContatoJv As String
	
	Private _EmailJv As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdClienteJvChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdClienteJvChanged()
    End Sub
    Partial Private Sub OnNomeCompletoJvChanging(value As String)
    End Sub
    Partial Private Sub OnNomeCompletoJvChanged()
    End Sub
    Partial Private Sub OnTipoDocJvChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnTipoDocJvChanged()
    End Sub
    Partial Private Sub OnDOCJvChanging(value As String)
    End Sub
    Partial Private Sub OnDOCJvChanged()
    End Sub
    Partial Private Sub OnRG_IEJvChanging(value As String)
    End Sub
    Partial Private Sub OnRG_IEJvChanged()
    End Sub
    Partial Private Sub OnEnderecoJvChanging(value As String)
    End Sub
    Partial Private Sub OnEnderecoJvChanged()
    End Sub
    Partial Private Sub OnBairroJvChanging(value As String)
    End Sub
    Partial Private Sub OnBairroJvChanged()
    End Sub
    Partial Private Sub OnCidadeJvChanging(value As String)
    End Sub
    Partial Private Sub OnCidadeJvChanged()
    End Sub
    Partial Private Sub OnEstadoJvChanging(value As String)
    End Sub
    Partial Private Sub OnEstadoJvChanged()
    End Sub
    Partial Private Sub OnPaisJvChanging(value As String)
    End Sub
    Partial Private Sub OnPaisJvChanged()
    End Sub
    Partial Private Sub OnCepJvChanging(value As String)
    End Sub
    Partial Private Sub OnCepJvChanged()
    End Sub
    Partial Private Sub OnTelefoneJvChanging(value As String)
    End Sub
    Partial Private Sub OnTelefoneJvChanged()
    End Sub
    Partial Private Sub OnCelularJvChanging(value As String)
    End Sub
    Partial Private Sub OnCelularJvChanged()
    End Sub
    Partial Private Sub OnWhattsappJvChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnWhattsappJvChanged()
    End Sub
    Partial Private Sub OnContatoJvChanging(value As String)
    End Sub
    Partial Private Sub OnContatoJvChanged()
    End Sub
    Partial Private Sub OnCelularContatoJvChanging(value As String)
    End Sub
    Partial Private Sub OnCelularContatoJvChanged()
    End Sub
    Partial Private Sub OnEmailJvChanging(value As String)
    End Sub
    Partial Private Sub OnEmailJvChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdClienteJv", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdClienteJv() As Integer
		Get
			Return Me._IdClienteJv
		End Get
		Set
			If ((Me._IdClienteJv = value)  _
						= false) Then
				Me.OnIdClienteJvChanging(value)
				Me.SendPropertyChanging
				Me._IdClienteJv = value
				Me.SendPropertyChanged("IdClienteJv")
				Me.OnIdClienteJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomeCompletoJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property NomeCompletoJv() As String
		Get
			Return Me._NomeCompletoJv
		End Get
		Set
			If (String.Equals(Me._NomeCompletoJv, value) = false) Then
				Me.OnNomeCompletoJvChanging(value)
				Me.SendPropertyChanging
				Me._NomeCompletoJv = value
				Me.SendPropertyChanged("NomeCompletoJv")
				Me.OnNomeCompletoJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TipoDocJv", DbType:="Bit")>  _
	Public Property TipoDocJv() As System.Nullable(Of Boolean)
		Get
			Return Me._TipoDocJv
		End Get
		Set
			If (Me._TipoDocJv.Equals(value) = false) Then
				Me.OnTipoDocJvChanging(value)
				Me.SendPropertyChanging
				Me._TipoDocJv = value
				Me.SendPropertyChanged("TipoDocJv")
				Me.OnTipoDocJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DOCJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property DOCJv() As String
		Get
			Return Me._DOCJv
		End Get
		Set
			If (String.Equals(Me._DOCJv, value) = false) Then
				Me.OnDOCJvChanging(value)
				Me.SendPropertyChanging
				Me._DOCJv = value
				Me.SendPropertyChanged("DOCJv")
				Me.OnDOCJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RG_IEJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property RG_IEJv() As String
		Get
			Return Me._RG_IEJv
		End Get
		Set
			If (String.Equals(Me._RG_IEJv, value) = false) Then
				Me.OnRG_IEJvChanging(value)
				Me.SendPropertyChanging
				Me._RG_IEJv = value
				Me.SendPropertyChanged("RG_IEJv")
				Me.OnRG_IEJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EnderecoJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property EnderecoJv() As String
		Get
			Return Me._EnderecoJv
		End Get
		Set
			If (String.Equals(Me._EnderecoJv, value) = false) Then
				Me.OnEnderecoJvChanging(value)
				Me.SendPropertyChanging
				Me._EnderecoJv = value
				Me.SendPropertyChanged("EnderecoJv")
				Me.OnEnderecoJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BairroJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property BairroJv() As String
		Get
			Return Me._BairroJv
		End Get
		Set
			If (String.Equals(Me._BairroJv, value) = false) Then
				Me.OnBairroJvChanging(value)
				Me.SendPropertyChanging
				Me._BairroJv = value
				Me.SendPropertyChanged("BairroJv")
				Me.OnBairroJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CidadeJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property CidadeJv() As String
		Get
			Return Me._CidadeJv
		End Get
		Set
			If (String.Equals(Me._CidadeJv, value) = false) Then
				Me.OnCidadeJvChanging(value)
				Me.SendPropertyChanging
				Me._CidadeJv = value
				Me.SendPropertyChanged("CidadeJv")
				Me.OnCidadeJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EstadoJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property EstadoJv() As String
		Get
			Return Me._EstadoJv
		End Get
		Set
			If (String.Equals(Me._EstadoJv, value) = false) Then
				Me.OnEstadoJvChanging(value)
				Me.SendPropertyChanging
				Me._EstadoJv = value
				Me.SendPropertyChanged("EstadoJv")
				Me.OnEstadoJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PaisJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property PaisJv() As String
		Get
			Return Me._PaisJv
		End Get
		Set
			If (String.Equals(Me._PaisJv, value) = false) Then
				Me.OnPaisJvChanging(value)
				Me.SendPropertyChanging
				Me._PaisJv = value
				Me.SendPropertyChanged("PaisJv")
				Me.OnPaisJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CepJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property CepJv() As String
		Get
			Return Me._CepJv
		End Get
		Set
			If (String.Equals(Me._CepJv, value) = false) Then
				Me.OnCepJvChanging(value)
				Me.SendPropertyChanging
				Me._CepJv = value
				Me.SendPropertyChanged("CepJv")
				Me.OnCepJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TelefoneJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property TelefoneJv() As String
		Get
			Return Me._TelefoneJv
		End Get
		Set
			If (String.Equals(Me._TelefoneJv, value) = false) Then
				Me.OnTelefoneJvChanging(value)
				Me.SendPropertyChanging
				Me._TelefoneJv = value
				Me.SendPropertyChanged("TelefoneJv")
				Me.OnTelefoneJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CelularJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property CelularJv() As String
		Get
			Return Me._CelularJv
		End Get
		Set
			If (String.Equals(Me._CelularJv, value) = false) Then
				Me.OnCelularJvChanging(value)
				Me.SendPropertyChanging
				Me._CelularJv = value
				Me.SendPropertyChanged("CelularJv")
				Me.OnCelularJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WhattsappJv", DbType:="Bit")>  _
	Public Property WhattsappJv() As System.Nullable(Of Boolean)
		Get
			Return Me._WhattsappJv
		End Get
		Set
			If (Me._WhattsappJv.Equals(value) = false) Then
				Me.OnWhattsappJvChanging(value)
				Me.SendPropertyChanging
				Me._WhattsappJv = value
				Me.SendPropertyChanged("WhattsappJv")
				Me.OnWhattsappJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ContatoJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property ContatoJv() As String
		Get
			Return Me._ContatoJv
		End Get
		Set
			If (String.Equals(Me._ContatoJv, value) = false) Then
				Me.OnContatoJvChanging(value)
				Me.SendPropertyChanging
				Me._ContatoJv = value
				Me.SendPropertyChanged("ContatoJv")
				Me.OnContatoJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CelularContatoJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property CelularContatoJv() As String
		Get
			Return Me._CelularContatoJv
		End Get
		Set
			If (String.Equals(Me._CelularContatoJv, value) = false) Then
				Me.OnCelularContatoJvChanging(value)
				Me.SendPropertyChanging
				Me._CelularContatoJv = value
				Me.SendPropertyChanged("CelularContatoJv")
				Me.OnCelularContatoJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmailJv", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property EmailJv() As String
		Get
			Return Me._EmailJv
		End Get
		Set
			If (String.Equals(Me._EmailJv, value) = false) Then
				Me.OnEmailJvChanging(value)
				Me.SendPropertyChanging
				Me._EmailJv = value
				Me.SendPropertyChanged("EmailJv")
				Me.OnEmailJvChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ProdutosJV")>  _
Partial Public Class ProdutosJV
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdProdutoJV As Integer
	
	Private _DescricaoJV As String
	
	Private _StatusJv As System.Nullable(Of Boolean)
	
	Private _Modulo As String
	
	Private _VlrDesk As System.Nullable(Of Decimal)
	
	Private _VlrMobile As System.Nullable(Of Decimal)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdProdutoJVChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdProdutoJVChanged()
    End Sub
    Partial Private Sub OnDescricaoJVChanging(value As String)
    End Sub
    Partial Private Sub OnDescricaoJVChanged()
    End Sub
    Partial Private Sub OnStatusJvChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnStatusJvChanged()
    End Sub
    Partial Private Sub OnModuloChanging(value As String)
    End Sub
    Partial Private Sub OnModuloChanged()
    End Sub
    Partial Private Sub OnVlrDeskChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVlrDeskChanged()
    End Sub
    Partial Private Sub OnVlrMobileChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVlrMobileChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdProdutoJV", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdProdutoJV() As Integer
		Get
			Return Me._IdProdutoJV
		End Get
		Set
			If ((Me._IdProdutoJV = value)  _
						= false) Then
				Me.OnIdProdutoJVChanging(value)
				Me.SendPropertyChanging
				Me._IdProdutoJV = value
				Me.SendPropertyChanged("IdProdutoJV")
				Me.OnIdProdutoJVChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DescricaoJV", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property DescricaoJV() As String
		Get
			Return Me._DescricaoJV
		End Get
		Set
			If (String.Equals(Me._DescricaoJV, value) = false) Then
				Me.OnDescricaoJVChanging(value)
				Me.SendPropertyChanging
				Me._DescricaoJV = value
				Me.SendPropertyChanged("DescricaoJV")
				Me.OnDescricaoJVChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StatusJv", DbType:="Bit")>  _
	Public Property StatusJv() As System.Nullable(Of Boolean)
		Get
			Return Me._StatusJv
		End Get
		Set
			If (Me._StatusJv.Equals(value) = false) Then
				Me.OnStatusJvChanging(value)
				Me.SendPropertyChanging
				Me._StatusJv = value
				Me.SendPropertyChanged("StatusJv")
				Me.OnStatusJvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Modulo", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Modulo() As String
		Get
			Return Me._Modulo
		End Get
		Set
			If (String.Equals(Me._Modulo, value) = false) Then
				Me.OnModuloChanging(value)
				Me.SendPropertyChanging
				Me._Modulo = value
				Me.SendPropertyChanged("Modulo")
				Me.OnModuloChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VlrDesk", DbType:="Money")>  _
	Public Property VlrDesk() As System.Nullable(Of Decimal)
		Get
			Return Me._VlrDesk
		End Get
		Set
			If (Me._VlrDesk.Equals(value) = false) Then
				Me.OnVlrDeskChanging(value)
				Me.SendPropertyChanging
				Me._VlrDesk = value
				Me.SendPropertyChanged("VlrDesk")
				Me.OnVlrDeskChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VlrMobile", DbType:="Money")>  _
	Public Property VlrMobile() As System.Nullable(Of Decimal)
		Get
			Return Me._VlrMobile
		End Get
		Set
			If (Me._VlrMobile.Equals(value) = false) Then
				Me.OnVlrMobileChanging(value)
				Me.SendPropertyChanging
				Me._VlrMobile = value
				Me.SendPropertyChanged("VlrMobile")
				Me.OnVlrMobileChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.LicensasIara")>  _
Partial Public Class LicensasIara
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IdDispositivoIARA As Integer
	
	Private _IDChaveIARA As Integer
	
	Private _DispositivoClienteIARA As String
	
	Private _TipoLicencaIARA As System.Nullable(Of Boolean)
	
	Private _MacAddressIARA As String
	
	Private _IpInt As String
	
	Private _Ipext As String
	
	Private _IdCliente As System.Nullable(Of Integer)
	
	Private _Modulo As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdDispositivoIARAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdDispositivoIARAChanged()
    End Sub
    Partial Private Sub OnIDChaveIARAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChaveIARAChanged()
    End Sub
    Partial Private Sub OnDispositivoClienteIARAChanging(value As String)
    End Sub
    Partial Private Sub OnDispositivoClienteIARAChanged()
    End Sub
    Partial Private Sub OnTipoLicencaIARAChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnTipoLicencaIARAChanged()
    End Sub
    Partial Private Sub OnMacAddressIARAChanging(value As String)
    End Sub
    Partial Private Sub OnMacAddressIARAChanged()
    End Sub
    Partial Private Sub OnIpIntChanging(value As String)
    End Sub
    Partial Private Sub OnIpIntChanged()
    End Sub
    Partial Private Sub OnIpextChanging(value As String)
    End Sub
    Partial Private Sub OnIpextChanged()
    End Sub
    Partial Private Sub OnIdClienteChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIdClienteChanged()
    End Sub
    Partial Private Sub OnModuloChanging(value As String)
    End Sub
    Partial Private Sub OnModuloChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdDispositivoIARA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IdDispositivoIARA() As Integer
		Get
			Return Me._IdDispositivoIARA
		End Get
		Set
			If ((Me._IdDispositivoIARA = value)  _
						= false) Then
				Me.OnIdDispositivoIARAChanging(value)
				Me.SendPropertyChanging
				Me._IdDispositivoIARA = value
				Me.SendPropertyChanged("IdDispositivoIARA")
				Me.OnIdDispositivoIARAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDChaveIARA", DbType:="Int NOT NULL")>  _
	Public Property IDChaveIARA() As Integer
		Get
			Return Me._IDChaveIARA
		End Get
		Set
			If ((Me._IDChaveIARA = value)  _
						= false) Then
				Me.OnIDChaveIARAChanging(value)
				Me.SendPropertyChanging
				Me._IDChaveIARA = value
				Me.SendPropertyChanged("IDChaveIARA")
				Me.OnIDChaveIARAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DispositivoClienteIARA", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property DispositivoClienteIARA() As String
		Get
			Return Me._DispositivoClienteIARA
		End Get
		Set
			If (String.Equals(Me._DispositivoClienteIARA, value) = false) Then
				Me.OnDispositivoClienteIARAChanging(value)
				Me.SendPropertyChanging
				Me._DispositivoClienteIARA = value
				Me.SendPropertyChanged("DispositivoClienteIARA")
				Me.OnDispositivoClienteIARAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TipoLicencaIARA", DbType:="Bit")>  _
	Public Property TipoLicencaIARA() As System.Nullable(Of Boolean)
		Get
			Return Me._TipoLicencaIARA
		End Get
		Set
			If (Me._TipoLicencaIARA.Equals(value) = false) Then
				Me.OnTipoLicencaIARAChanging(value)
				Me.SendPropertyChanging
				Me._TipoLicencaIARA = value
				Me.SendPropertyChanged("TipoLicencaIARA")
				Me.OnTipoLicencaIARAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MacAddressIARA", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property MacAddressIARA() As String
		Get
			Return Me._MacAddressIARA
		End Get
		Set
			If (String.Equals(Me._MacAddressIARA, value) = false) Then
				Me.OnMacAddressIARAChanging(value)
				Me.SendPropertyChanging
				Me._MacAddressIARA = value
				Me.SendPropertyChanged("MacAddressIARA")
				Me.OnMacAddressIARAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IpInt", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property IpInt() As String
		Get
			Return Me._IpInt
		End Get
		Set
			If (String.Equals(Me._IpInt, value) = false) Then
				Me.OnIpIntChanging(value)
				Me.SendPropertyChanging
				Me._IpInt = value
				Me.SendPropertyChanged("IpInt")
				Me.OnIpIntChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ipext", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Ipext() As String
		Get
			Return Me._Ipext
		End Get
		Set
			If (String.Equals(Me._Ipext, value) = false) Then
				Me.OnIpextChanging(value)
				Me.SendPropertyChanging
				Me._Ipext = value
				Me.SendPropertyChanged("Ipext")
				Me.OnIpextChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdCliente", DbType:="Int")>  _
	Public Property IdCliente() As System.Nullable(Of Integer)
		Get
			Return Me._IdCliente
		End Get
		Set
			If (Me._IdCliente.Equals(value) = false) Then
				Me.OnIdClienteChanging(value)
				Me.SendPropertyChanging
				Me._IdCliente = value
				Me.SendPropertyChanged("IdCliente")
				Me.OnIdClienteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Modulo", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Modulo() As String
		Get
			Return Me._Modulo
		End Get
		Set
			If (String.Equals(Me._Modulo, value) = false) Then
				Me.OnModuloChanging(value)
				Me.SendPropertyChanging
				Me._Modulo = value
				Me.SendPropertyChanged("Modulo")
				Me.OnModuloChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
